### ISSUE TITLE
Set Solver Config Server API

### ISSUE THREAD

**Issue by LeoAlle** [NVIDIA/cuOpt-Resources#19]
Hi, 
can you explain to me what is "number_of_climbers" in the solver configuration?
I know that the primary objective of the solver is to minimize the number of vehicles used, but I'd like to know which are the default values for the "Objectives" in the solver configuration, thanks.

**Comment by rg20** [comment]
Hi @LeoAlle, 

> Hi, can you explain to me what is "number_of_climbers" in the solver configuration? 

"number_of_climbers" is the number of parallel solutions considered at a time. This allows the solver to diversify the search space, more climbers mean more diversity. But that does not necessarily mean improved solution quality. This is because the run time and memory usage increase. If it is not provided by the user, the solver sets this value based on the problem size.   

> I know that the primary objective of the solver is to minimize the number of vehicles used, but I'd like to know which are the default values for the "Objectives" in the solver configuration, thanks. 
By default, the solver uses 2^32 as the weight for the vehicle count and 1 for the cost (cost is based on the specified cost matrix). For all other objectives, the weight is zero.

**Comment by LeoAlle** [comment]
Ok @rg20, thanks a lot for your quickly response.
