### ISSUE TITLE
Is there a way to get partial solution? [QST]

### ISSUE THREAD

**Issue by ajinra020307** [NVIDIA/cuOpt-Resources#24]
If i have 10 orders at different locations. I need atleast 10 vehicles to solve the problem.
If i dont provide enough vehicles the solve is fully failing
I need to know whether the solve can give a partial solution?

**Comment by rg20** [comment]
@ajinra020307, 

Typically, you would not need 10 vehicles for 10 orders, unless there are tight time window constraints on the vehicles or tight capacity/demand constraints.  

In the case that there are tight constraints and know that it is not feasible to satisfy all the orders, you can use `SolveInfeasible` function instead of `Solve`  which can return a partial solution and list of unfulfilled orders.

**Comment by ajinra020307** [comment]
@rg20 ok I will try that
